dist: trusty
sudo: required

jobs:
  include:
    - stage: Docker Build
      script:
      - docker build .
    - stage: Test
      script:
      - docker build -t softethervpn .
      - docker run softethervpn echo "[Travis CI OK]"
    - script:
      - docker build -t softethervpn .
      - docker network create --subnet 172.18.0.0/16 test-ipsec
      - docker run -d --cap-add NET_ADMIN -e USERNAME=test -e PASSWORD=test --network test-ipsec --ip 172.18.0.3 softethervpn
      - sudo bash tests/prepare-ipsec.sh
      - sudo bash tests/test-ipsec.sh
